In [1]:
import numpy as np
print(np.__version__)

2.2.2


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.array([0] * 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.ones([2,2], dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

In [6]:
np.ones([3,2], dtype= np.float16)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float16)

In [ ]:
X = np.arange(4, dtype=np.int8)

np.ones_like(X) # Convert any array into an array that filled with one.

[0 1 2 3]
[1 1 1 1]


In [11]:
X = np.array([[1,2,3],[1,2,3]])
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.ones([4,4], dtype=np.int8) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [14]:
X = np.array([[1,2,3],[1,2,3]], dtype=np.int8)
np.ones_like(X)*7

array([[7, 7, 7],
       [7, 7, 7]], dtype=int8)

In [18]:
A = np.zeros([3,3])
A[0, 0] = 1
A[1, 1] = 1
A[2, 2] = 1
A
A[0][0] = 10
A

array([[10.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.randint(10, size=3)

array([5, 4, 2], dtype=int32)

In [23]:
np.random.randint(10,size=(3,3,3))

array([[[8, 9, 1],
        [4, 6, 6],
        [6, 6, 4]],

       [[4, 2, 4],
        [4, 5, 5],
        [3, 0, 7]],

       [[1, 8, 3],
        [5, 7, 3],
        [8, 6, 5]]], dtype=int32)

In [24]:
np.random.randn(3,3,3)

array([[[ 0.35132255,  0.90708064,  1.63932046],
        [ 1.96299971,  1.82131648, -0.65787799],
        [ 1.20780753, -0.77019417, -0.90362209]],

       [[-2.43718803, -1.16664124,  1.59566952],
        [ 0.52426684, -0.41462833,  0.88152343],
        [-0.2953944 ,  1.72615767,  0.40414507]],

       [[ 0.08621515,  0.01830802, -0.88440859],
        [-0.20833167, -1.48797012, -0.65558816],
        [-0.03975488,  0.11664232,  0.89757886]]])

In [25]:
X = [1,2,3,4]
Y = np.array(X)
Y

array([1, 2, 3, 4])